### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by ZhanYang-Feng** [taichi-dev/Taichi-UnityExample#10]
It worked fine a month ago, but now it has a problem when running. My Unity version: 2021.3.6f1c1
![}B}VSC)E`{E9V$LP3(80%CW](https://user-images.githubusercontent.com/67536651/194185933-b21768b8-a4e1-4b5a-81c1-523d9b80d19c.png)

**Comment by PENGUINLIONG** [comment]
seems the aot module is out dated. could you try building taichi-unity.dll yourself and replacing the artifacts in the Plugins directory? you might also need to rerun the module scripts with a fresh taichi build.

**Comment by ZhanYang-Feng** [comment]
Sorry, maybe I didn't describe the problem clearly. The project that was cloned a month ago is still working fine. 2 days ago, I had this problem opening the latest version on my two devices. If the aot module is out dated, then there should be problems with pre versions as well?

**Comment by ZhanYang-Feng** [comment]
Sorry, maybe I didn't describe the problem clearly. The project that was cloned a month ago is still working fine. 2 days ago, I had this problem running the latest version on my two devices. If the aot module is out dated, then there should be problems with pre versions as well?

**Comment by PENGUINLIONG** [comment]
We have updated AOT modules and plugins within the last month and maybe that's the reason. Currently we haven't fully established a CI pipeline for these AOT demos so it breaks sometimes. We are working on CI improvements but the demos should work fine with a fresh build of `taichi_unity.dll` because it's already guarded by the main branch CI.

**Comment by ZhanYang-Feng** [comment]
Ok, I will try building taichi_unity.dll. Another question is that I have tried the AOT module builder, but I don't know how to convert LL and TCB flies to the AotModuleAsset which is in Unity. Is this still in development or is there already some way of doing the convert?

**Comment by PENGUINLIONG** [comment]
please refer to the generator scripts in the `scripts` directory. they will generate tcm files in `Assets/Resources`

**Comment by ZhanYang-Feng** [comment]
Thanks，I should use `archive` instead of `save` to get the tcm flie.
