### ISSUE TITLE
Load AOT Module Crash

### ISSUE THREAD

**Issue by maajor** [taichi-dev/Taichi-UnityExample#8]
![微信图片_20220809164641](https://user-images.githubusercontent.com/4011861/183607528-1b96e2fe-51d4-40f2-af50-e140d90939cb.jpg)
![微信图片_20220809164646](https://user-images.githubusercontent.com/4011861/183607535-9e821715-e77c-4bb2-b4ee-63090355e5e2.jpg)

版本 Windows 11
版本 21H2
安装日期 ‎2022/‎6/‎17
操作系统版本 22000.739

**Comment by PENGUINLIONG** [comment]
It should have been fixed by a recent update. Please feel free to reopen this if anything does wrong again :)
